<?php

namespace AppBundle\Repository;

/**
 * DonateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonateRepository extends \Doctrine\ORM\EntityRepository
{
}
